---
# Install and configure containerd
- name: Install prerequisites for containerd (Debian)
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  when: ansible_os_family == "Debian"

- name: Add containerd repository (Debian/Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker GPG key (Debian/Ubuntu)
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add containerd repository (RHEL/CentOS)
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    state: present
  when: ansible_os_family == "RedHat"

- name: Install containerd
  package:
    name: containerd.io
    state: present

- name: Configure containerd systemd drop-in
  copy:
    dest: /etc/systemd/system/containerd.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/containerd --config /etc/containerd/config.toml
    mode: '0644'
  notify: restart containerd

- name: Generate containerd config
  shell: containerd config default | tee /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Configure containerd to use systemd cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^            SystemdCgroup = '
    line: '            SystemdCgroup = true'
    backup: yes

- name: Start and enable containerd
  systemd:
    name: containerd
    enabled: true
    state: started
    daemon_reload: true

