---
# Handlers
- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: true

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    daemon_reload: true

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: true

- name: reload sysctl
  command: sysctl --system
  listen: reload sysctl

